// What the player page may ask of the app: its library file, picking and scanning folders, and the web source window.
const { contextBridge, ipcRenderer, webUtils } = require('electron');
const on = (ch, fn) => { const h = (e, v) => fn(v); ipcRenderer.on(ch, h); return () => ipcRenderer.removeListener(ch, h); };
// exposed as deskNative; the page's desk-boot.js copies it into window.desk, which remote control (lan.js) may stand in for
contextBridge.exposeInMainWorld('deskNative', {
  loadLib: () => ipcRenderer.invoke('lib-load'),
  saveLib: data => ipcRenderer.invoke('lib-save', data),
  pickFolder: () => ipcRenderer.invoke('pick-folder'),
  pickFiles: kind => ipcRenderer.invoke('pick-files', kind),
  scan: paths => ipcRenderer.invoke('scan', paths),
  exists: paths => ipcRenderer.invoke('exists', paths),
  readFile: p => ipcRenderer.invoke('read-file', p),
  pathOf: file => { try { return webUtils.getPathForFile(file); } catch { return ''; } },
  webOpen: url => ipcRenderer.invoke('web-open', url),
  webNav: cmd => ipcRenderer.invoke('web-nav', cmd),
  webMedia: play => ipcRenderer.invoke('web-media', play),
  webState: () => ipcRenderer.invoke('web-state'),
  onWeb: fn => on('web', fn),
  onKey: fn => on('key', fn),
  onCloseAsked: fn => on('close-asked', fn),
  quitOk: () => ipcRenderer.send('quit-ok'),
  mini: (v, height) => ipcRenderer.invoke('mini', v, height),
  winCmd: (c, arg) => ipcRenderer.send('win:cmd', c, arg),
  yt: {
    status: () => ipcRenderer.invoke('yt-status'),
    install: () => ipcRenderer.invoke('yt-install'),
    update: () => ipcRenderer.invoke('yt-update'),
    search: (q, n) => ipcRenderer.invoke('yt-search', q, n),
    info: url => ipcRenderer.invoke('yt-info', url),
    stream: url => ipcRenderer.invoke('yt-stream', url),
    download: (url, job) => ipcRenderer.invoke('yt-download', { url, job }),
    cancel: job => ipcRenderer.invoke('yt-cancel', job),
    folder: () => ipcRenderer.invoke('yt-folder'),
    onProgress: fn => on('yt:progress', fn)
  },
  scape: {
    list: () => ipcRenderer.invoke('scape-list'),
    get: id => ipcRenderer.invoke('scape-get', id),
    save: doc => ipcRenderer.invoke('scape-save', doc),
    patch: (id, p) => ipcRenderer.invoke('scape-patch', id, p),
    remove: id => ipcRenderer.invoke('scape-delete', id),
    import: () => ipcRenderer.invoke('scape-import'),
    edit: id => ipcRenderer.invoke('scape-edit', id),
    cmd: msg => ipcRenderer.send('scape:cmd', msg),
    state: st => ipcRenderer.send('scape:state', st),
    saveLoop: (name, bytes) => ipcRenderer.invoke('scape-loop-save', name, bytes),
    nodes: () => ipcRenderer.invoke('scape-nodes'),
    folder: sub => ipcRenderer.invoke('cs-folder', sub),
    onSaved: fn => on('scape:saved', fn),
    onCmd: fn => on('scape:cmd', fn),
    onState: fn => on('scape:state', fn)
  },
  bot: {
    cfg: () => ipcRenderer.invoke('bot-cfg'),
    login: (svc, token, origin) => ipcRenderer.invoke('bot-login', svc, token, origin),
    join: (svc, guild, channel) => ipcRenderer.invoke('bot-join', svc, guild, channel),
    leave: svc => ipcRenderer.invoke('bot-leave', svc),
    logout: (svc, forget) => ipcRenderer.invoke('bot-logout', svc, forget),
    set: (svc, k, v) => ipcRenderer.invoke('bot-set', svc, k, v),
    pcm: buf => ipcRenderer.send('bot-pcm', buf),
    note: text => ipcRenderer.send('bot-note', text),
    check: () => ipcRenderer.invoke('bot-check'),
    onEvent: fn => on('bot:ev', fn)
  },
  sysLang: () => ipcRenderer.invoke('sys-lang'),
  setLang: l => ipcRenderer.invoke('set-lang', l),
  reloadAll: () => ipcRenderer.invoke('reload-all'),
  csDir: () => ipcRenderer.invoke('cs-dir'),
  csDirPick: reset => ipcRenderer.invoke('cs-dir-pick', reset),
  dataFolder: () => ipcRenderer.invoke('data-folder'),
  libBackup: () => ipcRenderer.invoke('lib-backup'),
  mediaKeys: on => ipcRenderer.invoke('media-keys', on),
  onWinState: fn => on('win:state', fn),
  openExternal: url => ipcRenderer.invoke('open-external', url),
  hostName: () => ipcRenderer.invoke('host-name'),
  showItem: p => ipcRenderer.invoke('show-item', p),
  catalog: (name, fresh) => ipcRenderer.invoke('catalog', name, fresh),
  webGet: (url, headers) => ipcRenderer.invoke('web-get', url, headers),
  download: o => ipcRenderer.invoke('download', o),
  // updates from GitHub: { auto, skip, version, repo, changelog }, the on-start setting, a check now, the GitHub page
  updates: {
    get: () => ipcRenderer.invoke('upd:get'),
    set: auto => ipcRenderer.invoke('upd:set', { auto: !!auto }),
    check: () => ipcRenderer.invoke('upd:check'),
    github: () => ipcRenderer.invoke('upd:github')
  }
});
