/* Critter Sounds auf Deutsch, Teil 2: Klanglandschaften, Editor, Knoten, Touren, Einrichtung, Bots, Einstellungen,
   und Muster für Texte mit Zahlen und Namen darin. */
'use strict';
Object.assign(window.I18N_DE, {
  // ---------- Klanglandschaften (Hauptfenster) ----------
  '＋ New': '＋ Neu', 'New soundscape': 'Neue Klanglandschaft', 'Open the Soundscapes folder': 'Ordner „Soundscapes“ öffnen', 'Bring in a soundscape file…': 'Klanglandschaftsdatei hereinholen…', 'Rendered loops': 'Gerenderte Schleifen', 'Your own nodes': 'Eigene Knoten', 'Read the soundscape files again': 'Klanglandschaftsdateien neu einlesen', 'Reading the soundscapes…': 'Lese Klanglandschaften…',
  'A soundscape layers loops, one-off sounds at random moments and slow changes into a living background: rain that comes and goes, a tavern with the odd clatter. Only one plays at a time. Its files are in Music › Critter Sounds › Soundscapes.': 'Eine Klanglandschaft schichtet Schleifen, einzelne Klänge zu zufälligen Momenten und langsame Veränderungen zu einem lebendigen Hintergrund: Regen, der kommt und geht, eine Taverne mit gelegentlichem Klappern. Es spielt immer nur eine. Die Dateien liegen in Musik › Critter Sounds › Soundscapes.',
  'Name it: Rainy tavern, Haunted crypt…': 'Benenne sie: Verregnete Taverne, Spukgruft…', 'Double-click to rename': 'Doppelklick zum Umbenennen', 'Change the icon': 'Symbol ändern', 'Change the icon…': 'Symbol ändern…', 'From the name': 'Aus dem Namen', 'Make a copy': 'Kopie anlegen', 'Show the file': 'Datei zeigen', 'Move to the recycle bin': 'In den Papierkorb verschieben',
  'Play it to the table (fades over from any other soundscape)': 'Am Tisch abspielen (blendet von einer anderen Klanglandschaft über)', 'Fade it out': 'Ausblenden', 'Open the node editor in its own window': 'Den Knoten-Editor in einem eigenen Fenster öffnen', 'Empty: press Edit to build it': 'Leer: Drück Bearbeiten, um sie zu bauen', 'a soundscape': 'eine Klanglandschaft', 'Untitled soundscape': 'Unbenannte Klanglandschaft', 'Soundscape': 'Klanglandschaft',

  // ---------- Editor ----------
  'Soundscape editor': 'Klanglandschafts-Editor', 'Name this soundscape': 'Benenne diese Klanglandschaft', 'The soundscape\'s icon is picked in the main window': 'Das Symbol der Klanglandschaft wird im Hauptfenster gewählt',
  'Play to the table': 'Am Tisch abspielen', 'Playing in Critter Sounds: changes are heard as you make them.': 'Läuft in Critter Sounds: Änderungen sind sofort zu hören.', 'Another soundscape is playing; this one would fade over it.': 'Eine andere Klanglandschaft läuft; diese würde darüber blenden.',
  'Saves on its own': 'Speichert von selbst', 'Show every node (F)': 'Alle Knoten zeigen (F)', 'Render a loop': 'Schleife rendern', 'Render a seamless loop to a WAV file': 'Eine nahtlose Schleife als WAV-Datei rendern', 'The guided first loop, and how it works': 'Die geführte erste Schleife und wie alles funktioniert', 'Find a node…': 'Knoten suchen…', 'Add a node…': 'Knoten hinzufügen…', 'No node fits that.': 'Kein Knoten passt dazu.',
  'Start with a sound': 'Fang mit einem Klang an', 'Pick a node on the left (a Bed for rain or wind, a Sample for one-off sounds), or drop sound files here. Then drag from its blue dot to the Output\'s.': 'Wähle links einen Knoten (ein Bett für Regen oder Wind, ein Sample für einzelne Klänge) oder zieh Klangdateien hierher. Zieh dann von seinem blauen Punkt zu dem des Ausgangs.',
  'This node type isn\'t here: it may come from a file in Music › Critter Sounds › Nodes that is missing.': 'Diesen Knotentyp gibt es hier nicht: Er stammt vielleicht aus einer fehlenden Datei in Musik › Critter Sounds › Nodes.',
  'Hear the sound here, in this window': 'Den Klang hier hören, in diesem Fenster', 'Remove (Delete)': 'Entfernen (Entf)', 'Choose a sound…': 'Klang wählen…', 'A file…': 'Eine Datei…', 'Search your pads and playlists…': 'Deine Pads und Playlists durchsuchen…', 'Choose its sound first.': 'Wähle zuerst seinen Klang.', 'Double-click to type a value': 'Doppelklick, um einen Wert einzutippen', 'Applies when you click away (or Ctrl+Enter).': 'Wird übernommen, wenn du wegklickst (oder Strg+Enter).',
  'Music › Critter Sounds › Nodes: drop .js files there (see the README in it)': 'Musik › Critter Sounds › Nodes: Leg dort .js-Dateien ab (siehe README darin)',
  'Plays the soundscape here, silently and faster than real time, and saves it as a WAV file that loops without a seam: the end is crossfaded into the start. It goes to Music › Critter Sounds › Loops, ready for a playlist, a pad, or any other player.': 'Spielt die Klanglandschaft hier ab, lautlos und schneller als in Echtzeit, und speichert sie als WAV-Datei, die sich nahtlos wiederholt: Das Ende wird in den Anfang geblendet. Sie landet in Musik › Critter Sounds › Loops, bereit für eine Playlist, ein Pad oder jeden anderen Player.',
  'Length': 'Länge', 'Seam crossfade': 'Übergangsblende', 'File name': 'Dateiname', 'Render': 'Rendern', 'Loading the sounds…': 'Lade die Klänge…',
  'How soundscapes work': 'Wie Klanglandschaften funktionieren', 'Sound': 'Klang', 'Control: a slow number, about −1 to 1': 'Steuerung: eine langsame Zahl, etwa −1 bis 1', 'Trigger: "now!"': 'Auslöser: „jetzt!“', 'Keys': 'Tasten', 'Recipes': 'Rezepte', 'Learn the editor': 'Den Editor kennenlernen', 'Guided first loop': 'Geführte erste Schleife', 'Build the sound of the sea and save it as a loop': 'Den Klang des Meeres bauen und als Schleife speichern', 'How it works': 'So funktioniert es', 'Cables, nodes, keys and recipes': 'Kabel, Knoten, Tasten und Rezepte',
  'Double-click or Tab: add a node · Delete: remove · Ctrl+D: copy · Ctrl+Z / Ctrl+Y: undo / redo · F: show everything · Space: play or stop · scroll: zoom · drag the background: move around': 'Doppelklick oder Tab: Knoten hinzufügen · Entf: entfernen · Strg+D: kopieren · Strg+Z / Strg+Y: rückgängig / wiederholen · F: alles zeigen · Leertaste: abspielen oder stoppen · Scrollen: zoomen · Hintergrund ziehen: bewegen',
  'Distant thunder: Sometimes (every 40 s) → Sample (thunder, pitch varies 0.2) → Filter (lowpass) → Reverb (cave) → Output.': 'Fernes Gewitter: Manchmal (alle 40 s) → Sample (Donner, Tonhöhe variiert 0.2) → Filter (Tiefpass) → Hall (Höhle) → Ausgang.',
  'Busy tavern: Bed (tavern crowd) plus Sometimes → Pick one → three Samples (mugs, laughter, door), all into a Merge → Output.': 'Volle Taverne: Bett (Tavernengemurmel) plus Manchmal → Eins wählen → drei Samples (Krüge, Lachen, Tür), alle in ein Zusammenführen → Ausgang.',
  'Rising dread: Tone (low saw) → Filter → Level → Output, with a Macro into the Level\'s dot. Its slider on the tile swells the drone during play.': 'Wachsende Furcht: Ton (tiefe Sägezahnwelle) → Filter → Pegel → Ausgang, mit einem Makro am Punkt des Pegels. Sein Regler auf der Kachel lässt das Dröhnen im Spiel anschwellen.',
  'A Script node runs a few lines of JavaScript. For whole new node types, put a .js file in Music › Critter Sounds › Nodes: there\'s a README and an example there. Reopen the window to load changes.': 'Ein Skript-Knoten führt ein paar Zeilen JavaScript aus. Für ganz neue Knotentypen leg eine .js-Datei in Musik › Critter Sounds › Nodes: Dort gibt es eine README und ein Beispiel. Öffne das Fenster neu, um Änderungen zu laden.',

  // ---------- Knoten ----------
  'Sound sources': 'Klangquellen', 'Control': 'Steuerung', 'Triggers': 'Auslöser', 'Signal maths': 'Signal-Mathematik', 'Effects ': 'Effekte', 'Output': 'Ausgang', 'Custom': 'Eigene',
  'Sample': 'Sample', 'Bed': 'Bett', 'Noise': 'Rauschen', 'Tone': 'Ton', 'LFO': 'LFO', 'Drift': 'Drift', 'Value': 'Wert', 'Macro': 'Makro', 'Script': 'Skript', 'Clock': 'Takt', 'Sometimes': 'Manchmal', 'Sequencer': 'Sequenzer', 'Chance': 'Zufall', 'Wait': 'Warten', 'Every Nth': 'Jedes N-te', 'Pick one': 'Eins wählen', 'Merge': 'Zusammenführen', 'Level': 'Pegel', 'Boost': 'Verstärken', 'Subtract': 'Abziehen', 'Invert': 'Umkehren', 'Multiply': 'Multiplizieren', 'Range': 'Bereich', 'Cutout': 'Ausschneiden', 'Smooth': 'Glätten', 'Absolute': 'Betrag', 'Filter': 'Filter', 'Echo': 'Echo', 'Reverb': 'Hall', 'Pan': 'Panorama', 'Distort': 'Verzerren', 'Even out': 'Ausgleichen', 'Music effects': 'Musikeffekte',
  'Volume': 'Lautstärke', 'Pitch': 'Tonhöhe', 'Pitch varies': 'Tonhöhe variiert', 'Loop while playing': 'Beim Abspielen wiederholen', 'At once': 'Gleichzeitig', 'Speed': 'Geschwindigkeit', 'Start somewhere random': 'An zufälliger Stelle beginnen', 'Colour': 'Farbe', 'White': 'Weiß', 'Pink': 'Rosa', 'Brown': 'Braun', 'Wave': 'Welle', 'Sine': 'Sinus', 'Triangle': 'Dreieck', 'Saw': 'Sägezahn', 'Square': 'Rechteck', 'Shape': 'Form', 'Depth': 'Tiefe', 'Offset': 'Versatz', 'Peak': 'Gipfel', 'Lowest': 'Niedrigster', 'Highest': 'Höchster', 'About every': 'Etwa alle', 'Glide': 'Gleiten', 'New value': 'Neuer Wert', 'Intensity': 'Intensität', 'Code': 'Code', 'Trigger': 'Auslöser', 'Fire': 'Auslösen', 'Every': 'Alle', 'Swing': 'Schwankung', 'Fire at the start': 'Am Anfang auslösen', 'Tick': 'Tick', 'On average every': 'Im Schnitt alle', 'At least': 'Mindestens', 'Now': 'Jetzt', 'Pattern': 'Muster', 'Step': 'Schritt', 'Hit': 'Schlag', 'In': 'Ein', 'Out': 'Aus', 'Later': 'Später', 'Varies by': 'Schwankt um', 'Outputs used': 'Genutzte Ausgänge', 'Mode': 'Modus', 'Threshold': 'Schwelle', 'Gate': 'Gate', 'Clip': 'Begrenzen', 'Type': 'Typ', 'Lowpass': 'Tiefpass', 'Highpass': 'Hochpass', 'Bandpass': 'Bandpass', 'Notch': 'Kerbfilter', 'Frequency': 'Frequenz', 'Resonance': 'Resonanz', 'Sweep': 'Schwenk', 'Time': 'Zeit', 'Repeats': 'Wiederholungen', 'Mix': 'Mischung', 'Space': 'Raum', 'Adjustable': 'Einstellbar', 'Wooden room': 'Holzraum', 'Great hall': 'Große Halle', 'Plate': 'Plattenhall', 'Size': 'Größe', 'Amount': 'Menge', 'Ratio': 'Verhältnis', 'Fades in over': 'Blendet ein über',
  'Plays a sound each time it is triggered, with a little variation if you like.': 'Spielt bei jedem Auslösen einen Klang, auf Wunsch mit etwas Abwechslung.', 'A sound that loops for as long as the soundscape plays: rain, wind, a tavern.': 'Ein Klang, der sich wiederholt, solange die Klanglandschaft läuft: Regen, Wind, eine Taverne.',
  'Endless noise: white is hiss, pink is rain-like, brown is a deep rumble. Filter it into wind or surf.': 'Endloses Rauschen: Weiß zischt, Rosa klingt wie Regen, Braun ist ein tiefes Grollen. Filtere es zu Wind oder Brandung.', 'A steady tone or drone. Wire a control into Pitch to make it bend.': 'Ein gleichmäßiger Ton oder Dröhnen. Verbinde eine Steuerung mit der Tonhöhe, um ihn zu biegen.',
  'A slow wave, from -1 to 1. Wire it into a knob to make that knob sway. Its Peak output fires at each top of the wave.': 'Eine langsame Welle von -1 bis 1. Verbinde sie mit einem Regler, damit er schwankt. Ihr Gipfel-Ausgang löst bei jedem Wellenberg aus.',
  'Wanders to a new random value now and then, smoothly: random bounces for anything. Fires a trigger each time it picks a new one.': 'Wandert ab und zu sanft zu einem neuen Zufallswert: zufällige Sprünge für alles. Löst bei jedem neuen Wert aus.',
  'A fixed number, for adding, offsetting or as a starting point.': 'Eine feste Zahl, zum Addieren, Versetzen oder als Ausgangspunkt.', 'A slider that shows on the soundscape\'s tile in the main window, for changing it while it plays: intensity, danger, weather…': 'Ein Regler auf der Kachel der Klanglandschaft im Hauptfenster, um sie während des Spiels zu verändern: Intensität, Gefahr, Wetter…',
  'Your own few lines of JavaScript, run 20 times a second of soundscape time.': 'Deine eigenen paar Zeilen JavaScript, 20-mal pro Sekunde Klanglandschaftszeit ausgeführt.', 'Fires every few seconds. Swing makes it less regular.': 'Löst alle paar Sekunden aus. Schwankung macht es unregelmäßiger.',
  'Fires at random moments, on average every so often, but never twice within the shortest gap.': 'Löst zu zufälligen Momenten aus, im Schnitt alle paar Sekunden, aber nie zweimal innerhalb des kürzesten Abstands.', 'Steps through a pattern: x fires, . waits. "x..x..x." is a rhythm; every step lasts Step long.': 'Geht ein Muster durch: x löst aus, . wartet. „x..x..x.“ ist ein Rhythmus; jeder Schritt dauert Schritt lang.',
  'Lets a trigger through only some of the time.': 'Lässt einen Auslöser nur manchmal durch.', 'Passes a trigger on a little later: thunder after lightning.': 'Gibt einen Auslöser etwas später weiter: Donner nach dem Blitz.', 'Passes every Nth trigger on: every 4th drum hit, every 3rd footstep.': 'Gibt jeden N-ten Auslöser weiter: jeden 4. Trommelschlag, jeden 3. Schritt.', 'Sends each trigger to one of its outputs at random, so several samples take turns.': 'Schickt jeden Auslöser zufällig an einen seiner Ausgänge, damit sich mehrere Samples abwechseln.',
  'Adds up to four signals into one: mix several sounds.': 'Fasst bis zu vier Signale zusammen: mischt mehrere Klänge.', 'Turns a signal up or down. Wire a control into Level to make it swell and fade.': 'Macht ein Signal lauter oder leiser. Verbinde eine Steuerung mit dem Pegel, damit es an- und abschwillt.', 'Makes a signal louder or quieter in decibels.': 'Macht ein Signal in Dezibel lauter oder leiser.',
  'Flips a signal: −x, or 1 − x (for 0..1 controls).': 'Dreht ein Signal um: −x oder 1 − x (für Steuerungen von 0..1).', 'A × B: B (a control from 0 to 1) sets how loud A is. A sound times an LFO is a tremolo.': 'A × B: B (eine Steuerung von 0 bis 1) bestimmt, wie laut A ist. Ein Klang mal ein LFO ergibt ein Tremolo.', 'Maps a −1..1 control onto Lowest..Highest.': 'Bildet eine Steuerung von −1..1 auf Niedrigster..Höchster ab.',
  'Gate: silences everything quieter than the threshold. Clip: flattens everything louder. Works on −1..1 signals.': 'Gate: macht alles stumm, was leiser als die Schwelle ist. Begrenzen: flacht alles Lautere ab. Für Signale von −1..1.', 'Takes the edges off a control: a jumpy value becomes a glide.': 'Glättet eine Steuerung: Aus einem sprunghaften Wert wird ein Gleiten.', 'Makes negative values positive: a −1..1 wave becomes two 0..1 humps.': 'Macht negative Werte positiv: Aus einer Welle von −1..1 werden zwei Buckel von 0..1.',
  'Lowpass makes things muffled or distant, highpass thin, bandpass like wind through a gap. Sweep moves it by up to two octaves.': 'Tiefpass macht dumpf oder fern, Hochpass dünn, Bandpass wie Wind durch einen Spalt. Schwenk verschiebt ihn um bis zu zwei Oktaven.', 'Repeats the sound, fading: canyons, halls, dreams.': 'Wiederholt den Klang, leiser werdend: Schluchten, Hallen, Träume.', 'Puts the sound in a space, from a small room to a cathedral.': 'Setzt den Klang in einen Raum, vom kleinen Zimmer bis zur Kathedrale.',
  'Places the sound left or right. An LFO into Pan makes it drift side to side.': 'Setzt den Klang nach links oder rechts. Ein LFO am Panorama lässt ihn hin und her wandern.', 'Grit and crunch: radios, machines, fire.': 'Körnigkeit und Biss: Radios, Maschinen, Feuer.', 'Evens out loud and quiet moments.': 'Gleicht laute und leise Momente aus.', 'All of Critter Sounds\' effects in one, as a preset: Underwater, Old gramophone, Haunted…': 'Alle Effekte von Critter Sounds in einem, als Voreinstellung: Unter Wasser, Altes Grammophon, Spukhaft…', 'Where the soundscape comes out. In the main window, that\'s the table.': 'Wo die Klanglandschaft herauskommt. Im Hauptfenster ist das der Tisch.',

  // ---------- Touren ----------
  'End the tour (Esc)': 'Tour beenden (Esc)', 'That\'s it!': 'Genau so!', 'Your turn: try it.': 'Du bist dran: Probier es aus.', 'Do it for me': 'Mach es für mich', 'Keep this layout': 'Dieses Layout behalten', 'Back to my layout': 'Zurück zu meinem Layout',
  'Tour ended: your layout is back as it was. Help › Quick tour starts it again.': 'Tour beendet: Dein Layout ist wieder wie vorher. Hilfe › Kurztour startet sie erneut.',
  'Welcome to Critter Sounds': 'Willkommen bei Critter Sounds', 'The full tour': 'Die komplette Tour', 'This quick tour takes about two minutes.': 'Diese Kurztour dauert etwa zwei Minuten.',
  'Critter Sounds plays music, sound effects and ambience for your tabletop game, live to everyone at your table.': 'Critter Sounds spielt Musik, Soundeffekte und Atmosphäre für dein Tabletop-Spiel, live für alle an deinem Tisch.',
  'It shows every window, what you can do with it, and how to arrange them. About ten minutes; you can stop at any time.': 'Sie zeigt jedes Fenster, was du damit tun kannst und wie du sie anordnest. Etwa zehn Minuten; du kannst jederzeit aufhören.',
  'The tour changes your layout as it goes. At the end you can keep the new one or go back to yours.': 'Die Tour ändert unterwegs dein Layout. Am Ende kannst du das neue behalten oder zu deinem zurückkehren.',
  'The canvas': 'Die Arbeitsfläche', 'This big space holds windows. Each window is one tool: your playlists, sound pads, soundscapes, effects and more. Right now it\'s empty.': 'Dieser große Bereich enthält Fenster. Jedes Fenster ist ein Werkzeug: deine Playlists, Sound-Pads, Klanglandschaften, Effekte und mehr. Gerade ist er leer.',
  'Windows adds a window': 'Fenster fügt ein Fenster hinzu', 'Click Windows and pick a tool: it opens on the canvas. Each new window shares the space with the ones already there.': 'Klick auf Fenster und wähle ein Werkzeug: Es öffnet sich auf der Arbeitsfläche. Jedes neue Fenster teilt sich den Platz mit den vorhandenen.', 'Every window has a short description in that list, so you can see what it\'s for before opening it.': 'Jedes Fenster hat in der Liste eine kurze Beschreibung, damit du vor dem Öffnen siehst, wofür es da ist.',
  'Layouts open several at once': 'Layouts öffnen mehrere auf einmal', 'A layout is a ready-made set of windows. We just picked "Simple player": your playlists beside their tracks.': 'Ein Layout ist eine fertige Fenster-Zusammenstellung. Wir haben gerade „Einfacher Player“ gewählt: deine Playlists neben ihren Titeln.', 'There are layouts for running a game, building playlists, making sound pads and playing to voice chat, and you can save your own.': 'Es gibt Layouts zum Spielleiten, Playlists-Zusammenstellen, Pads-Anlegen und Spielen im Sprachchat, und du kannst eigene speichern.',
  '"From a folder" turns a folder of music into a playlist, folders inside it included. Your files stay where they are: nothing is uploaded.': '„Aus einem Ordner“ macht aus einem Musikordner eine Playlist, Unterordner eingeschlossen. Deine Dateien bleiben, wo sie sind: Nichts wird hochgeladen.', '"＋ Empty" makes an empty one to fill from the online library or YouTube.': '„＋ Leer“ legt eine leere an, die du aus der Online-Bibliothek oder YouTube füllst.',
  'The tracks': 'Die Titel', 'Double-click a track to play it. Select tracks and press Q, or drag them onto the queue, to play them next. Right-click a track for more.': 'Doppelklick spielt einen Titel ab. Wähle Titel aus und drück Q oder zieh sie auf die Warteschlange, um sie als Nächstes zu spielen. Rechtsklick auf einen Titel für mehr.',
  'The queue plays first, then the playlist you played from carries on. Drag to reorder, ✕ to remove. Sound pads that are playing show up below it. ☰ Queue in the top bar hides or shows it.': 'Zuerst spielt die Warteschlange, dann geht es mit der Playlist weiter. Ziehen zum Umsortieren, ✕ zum Entfernen. Laufende Sound-Pads erscheinen darunter. ☰ Warteschlange in der oberen Leiste blendet sie ein oder aus.',
  '▶ plays and pauses, always with a gentle fade': '▶ spielt und pausiert, immer mit sanftem Blenden', '■ fades out; press it twice to stop at once': '■ blendet aus; zweimal drücken stoppt sofort', '⏮ ⏭ go back and ahead': '⏮ ⏭ zurück und vor', '⇄ shuffles, ⟳ repeats the playlist or one track': '⇄ mischt, ⟳ wiederholt die Playlist oder einen Titel',
  'Two volumes': 'Zwei Lautstärken', 'Table is how loud everyone hears it.': 'Tisch ist, wie laut alle es hören.', 'Here plays it on this computer too, with the effects, so you can listen along. Leave it off if Critter VTT is open on this computer as well, or you\'ll hear it twice.': 'Hier spielt es auch an diesem Computer, mit Effekten, damit du mithören kannst. Lass es aus, wenn hier auch Critter VTT offen ist, sonst hörst du es doppelt.',
  'Playing to your table': 'Für deinen Tisch spielen', 'In Critter VTT, the lobby owner opens the Music window and copies the music code. Paste it here and press Connect: everyone in the lobby hears what you play.': 'In Critter VTT öffnet der Lobby-Besitzer das Musikfenster und kopiert den Musikcode. Füge ihn hier ein und drück Verbinden: Alle in der Lobby hören, was du spielst.', 'Meeting in Discord or Fluxer instead? The "Discord & Fluxer" window puts a bot of your own in a voice channel.': 'Ihr trefft euch stattdessen in Discord oder Fluxer? Das Fenster „Discord & Fluxer“ setzt einen eigenen Bot in einen Sprachkanal.',
  'A layout for game night': 'Ein Layout für den Spieleabend', '"Run a game" puts playlists, sound pads, soundscapes, scenes and effects side by side, everything a session needs.': '„Spiel leiten“ stellt Playlists, Sound-Pads, Klanglandschaften, Szenen und Effekte nebeneinander, alles, was eine Sitzung braucht.', 'The full tour (in Help) explains each of these windows.': 'Die komplette Tour (in der Hilfe) erklärt jedes dieser Fenster.',
  'Make it yours': 'Mach es zu deinem', 'Every window has these buttons in its title bar:': 'Jedes Fenster hat diese Knöpfe in seiner Titelleiste:', '◫ splits it: a new window to the right. ⊟ splits it downwards': '◫ teilt es: ein neues Fenster rechts. ⊟ teilt nach unten', '⇄ shows something else in the same window': '⇄ zeigt etwas anderes im selben Fenster', '✕ closes it': '✕ schließt es',
  'Drag a window by its title onto another: near an edge it docks there, on the middle the two swap': 'Zieh ein Fenster an seinem Titel auf ein anderes: nahe einem Rand dockt es dort an, in der Mitte tauschen die beiden', 'Drag the line between two windows to resize them. It clicks into place at halves, thirds and quarters': 'Zieh die Linie zwischen zwei Fenstern, um ihre Größe zu ändern. Sie rastet bei Hälften, Dritteln und Vierteln ein',
  'Help is always here': 'Die Hilfe ist immer hier', 'Help has this tour, the full tour with every window, the setup, and the Help window with shortcuts.': 'In der Hilfe findest du diese Tour, die komplette Tour mit jedem Fenster, die Einrichtung und das Hilfefenster mit Tastenkürzeln.', 'Keep the "Run a game" layout, or go back to what you had?': 'Das Layout „Spiel leiten“ behalten oder zu deinem vorherigen zurück?',
  'Arranging windows': 'Fenster anordnen', 'Now one window fills the canvas. Watch the next steps change it, then try it yourself any time.': 'Jetzt füllt ein Fenster die Arbeitsfläche. Sieh zu, wie die nächsten Schritte es ändern, und probier es danach selbst aus.', '◫ Split': '◫ Teilen', 'Pressing ◫ in a window\'s title splits it: the new window opens on the right. Here, it shows the sound pads. ⊟ splits downwards instead.': '◫ im Titel eines Fensters teilt es: Das neue Fenster öffnet sich rechts. Hier zeigt es die Sound-Pads. ⊟ teilt stattdessen nach unten.',
  'Resize': 'Größe ändern', 'Drag the line between two windows to make one bigger. It clicks into place at halves, thirds and quarters (hold Alt to place it freely). Double-click the line to make both halves equal.': 'Zieh die Linie zwischen zwei Fenstern, um eines größer zu machen. Sie rastet bei Hälften, Dritteln und Vierteln ein (Alt halten für freie Platzierung). Doppelklick auf die Linie macht beide Hälften gleich.',
  '⇄ Show something else': '⇄ Etwas anderes zeigen', '⇄ swaps what a window shows without changing the layout: the pads window now shows the effects.': '⇄ tauscht den Inhalt eines Fensters, ohne das Layout zu ändern: Das Pad-Fenster zeigt jetzt die Effekte.', 'Dock: drag by the title': 'Andocken: am Titel ziehen', 'Drag a window by its title onto another one. Near an edge, it docks on that side; on the middle, the two trade places.': 'Zieh ein Fenster an seinem Titel auf ein anderes. Nahe einem Rand dockt es auf dieser Seite an; in der Mitte tauschen die beiden die Plätze.', 'We just docked the effects above the tracks.': 'Wir haben gerade die Effekte über den Titeln angedockt.',
  'Save your layout': 'Speichere dein Layout', 'Layouts › "Save this layout…" keeps an arrangement under a name, to come back to it with one click. "Clear the canvas" starts over.': 'Layouts › „Dieses Layout speichern…“ behält eine Anordnung unter einem Namen, um mit einem Klick zurückzukommen. „Arbeitsfläche leeren“ fängt neu an.',
  'Free music and sound effects from Tabletop Audio, Incompetech, Openverse and Freesound, each credited as it plays.': 'Freie Musik und Soundeffekte von Tabletop Audio, Incompetech, Openverse und Freesound, jeweils mit Quellenangabe beim Abspielen.', '🎧 previews on this computer only. + Queue, Playlist ▾ and Pad add a result; ⭳ saves it to play offline. Tick several to add them all at once.': '🎧 hört nur an diesem Computer vor. + Warteschlange, Playlist ▾ und Pad fügen ein Ergebnis hinzu; ⭳ speichert es für offline. Hake mehrere an, um alle auf einmal hinzuzufügen.',
  'Search YouTube or paste a link, listen first, and save just the sound to Music › Critter Sounds › YouTube. It lands in a "YouTube" playlist. Only download what you may use.': 'Durchsuche YouTube oder füge einen Link ein, hör zuerst rein und speichere nur den Ton nach Musik › Critter Sounds › YouTube. Er landet in einer Playlist „YouTube“. Lade nur herunter, was du nutzen darfst.',
  'Building a playlist': 'Eine Playlist zusammenstellen', 'The playlist on the right fills as you add from the online library or YouTube. The layout you\'re looking at is "Build playlists".': 'Die Playlist rechts füllt sich, während du aus der Online-Bibliothek oder YouTube hinzufügst. Das Layout, das du siehst, heißt „Playlists zusammenstellen“.',
  'One click plays a sound effect; a second click stops it. Keys 1 to 9 play the first nine.': 'Ein Klick spielt einen Soundeffekt, ein zweiter stoppt ihn. Die Tasten 1 bis 9 spielen die ersten neun.', 'Pads get an icon and a group by their name. Right-click one to change its group, tag, colour or icon. ⟳ makes a pad loop until you stop it; the music dips while a pad plays.': 'Pads bekommen anhand ihres Namens ein Symbol und eine Gruppe. Rechtsklick ändert Gruppe, Tag, Farbe oder Symbol. ⟳ wiederholt ein Pad, bis du es stoppst; die Musik wird leiser, während ein Pad spielt.',
  'A soundscape is a living background built from layers: rain that comes and goes, a tavern with the odd clatter.': 'Eine Klanglandschaft ist ein lebendiger Hintergrund aus Schichten: Regen, der kommt und geht, eine Taverne mit gelegentlichem Klappern.', '▶ plays one (only one at a time). ✎ Edit opens the soundscape editor, which has its own guided first loop.': '▶ spielt eine ab (immer nur eine). ✎ Bearbeiten öffnet den Klanglandschafts-Editor mit seiner eigenen geführten ersten Schleife.',
  'A scene remembers a playlist with its effects, volume and repeat. Starting one crossfades into it: from the tavern to a fight in one click.': 'Eine Szene merkt sich eine Playlist mit Effekten, Lautstärke und Wiederholen. Beim Start wird hineingeblendet: mit einem Klick von der Taverne in den Kampf.', 'Reverb, radio, muffle, crackle and more, with presets like "Underwater" and "Old gramophone". They play on everyone\'s computer and never make the music louder.': 'Hall, Radio, Dämpfung, Knistern und mehr, mit Voreinstellungen wie „Unter Wasser“ und „Altes Grammophon“. Sie laufen auf jedem Computer und machen die Musik nie lauter.',
  'How long songs take to fade in and out, and whether one track crossfades into the next.': 'Wie lange Titel zum Ein- und Ausblenden brauchen und ob ein Titel in den nächsten überblendet.', 'What played when, session by session. It also shows as small notes in Critter VTT\'s chat (you can switch that off), and Copy gives the text.': 'Was wann lief, Sitzung für Sitzung. Es erscheint auch als kleine Notizen in Critters Chat (abschaltbar), und Kopieren liefert den Text.',
  'Open any web page that plays sound, like an ambience site or a video, and its sound goes to the table.': 'Öffne eine beliebige Webseite mit Ton, etwa eine Atmosphären-Seite oder ein Video, und ihr Ton geht an den Tisch.', 'For groups that meet in a voice channel: a bot of your own joins and plays exactly what the table would hear. It signs in on its own once its token is saved.': 'Für Gruppen, die sich in einem Sprachkanal treffen: Ein eigener Bot tritt bei und spielt genau, was der Tisch hören würde. Er meldet sich von selbst an, sobald sein Token gespeichert ist.',
  'Change the highlight colours and the background: any colour you like.': 'Ändere die Akzentfarben und den Hintergrund: jede Farbe, die du magst.', 'A small player that stays on top of other apps (Ctrl+M), with Up next and a few pads. Handy while you run the game in Critter VTT.': 'Ein kleiner Player, der über anderen Apps bleibt (Strg+M), mit „Als Nächstes“ und ein paar Pads. Praktisch, während du das Spiel in Critter VTT leitest.',
  'That\'s everything': 'Das ist alles', 'Help has the quick tour, this tour, the setup, and the Help window with every shortcut.': 'In der Hilfe findest du die Kurztour, diese Tour, die Einrichtung und das Hilfefenster mit allen Tastenkürzeln.',
  'Your first soundscape loop': 'Deine erste Klanglandschafts-Schleife', 'Let\'s make the sound of the sea, from scratch: noise for the water, a slow wave for the surf. Then we\'ll save it as a loop you can play anywhere.': 'Bauen wir den Klang des Meeres von Grund auf: Rauschen für das Wasser, eine langsame Welle für die Brandung. Dann speichern wir sie als Schleife, die du überall abspielen kannst.',
  'It takes about three minutes and needs no sound files. Each step waits for you, and "Do it for me" is there if you\'d rather watch. Skip any time with ✕.': 'Es dauert etwa drei Minuten und braucht keine Klangdateien. Jeder Schritt wartet auf dich, und „Mach es für mich“ ist da, wenn du lieber zusiehst. Überspringe jederzeit mit ✕.',
  'Nodes and the Output': 'Knoten und der Ausgang', 'On the left are nodes, by kind: sound sources make sound, controls move knobs, triggers say "now", and effects change sound.': 'Links sind die Knoten, nach Art: Klangquellen machen Klang, Steuerungen bewegen Regler, Auslöser sagen „jetzt“ und Effekte verändern Klang.', 'Everything you hear goes into the Output (the green one). It\'s the only node that\'s here from the start.': 'Alles, was du hörst, geht in den Ausgang (den grünen). Er ist der einzige Knoten, der von Anfang an da ist.',
  'Add some water': 'Etwas Wasser hinzufügen', 'Sound sources make sound. Noise makes an endless hiss that sounds like water. Click Noise in the list (or drag it onto the canvas).': 'Klangquellen machen Klang. Rauschen macht ein endloses Zischen, das wie Wasser klingt. Klick in der Liste auf Rauschen (oder zieh es auf die Arbeitsfläche).', 'Click Noise in the list.': 'Klick in der Liste auf Rauschen.',
  'A deeper sea': 'Ein tieferes Meer', 'Every node has knobs. Set Colour to Brown: a deep rumble, like the sea from a cliff. (Pink is rain, white is hiss.)': 'Jeder Knoten hat Regler. Stell Farbe auf Braun: ein tiefes Grollen, wie das Meer von einer Klippe aus. (Rosa ist Regen, Weiß ist Zischen.)', 'Choose Brown in the Colour list.': 'Wähle Braun in der Farbliste.',
  'Plug it in': 'Einstecken', 'Cables carry sound from an output (the dots on the right of a node) to an input (on the left).': 'Kabel tragen Klang von einem Ausgang (den Punkten rechts an einem Knoten) zu einem Eingang (links).', 'Drag from the Noise\'s blue Sound dot to the Output\'s blue Sound dot.': 'Zieh vom blauen Klang-Punkt des Rauschens zum blauen Klang-Punkt des Ausgangs.', 'Drag from one blue dot to the other.': 'Zieh von einem blauen Punkt zum anderen.',
  'Hear it': 'Hör es dir an', 'Play sends it to the table, through Critter Sounds\' main window, like everything else you play.': 'Abspielen schickt es an den Tisch, über das Hauptfenster von Critter Sounds, wie alles andere, was du spielst.', 'To hear it yourself, "Here" must be on in the main window\'s bottom bar. "Do it for me" turns it on and plays.': 'Um es selbst zu hören, muss „Hier“ in der unteren Leiste des Hauptfensters an sein. „Mach es für mich“ schaltet es ein und spielt ab.', 'Press Play to the table.': 'Drück „Am Tisch abspielen“.',
  'Now the waves': 'Jetzt die Wellen', 'Controls don\'t make sound: they move knobs. An LFO is a slow wave that goes up and down. Add one.': 'Steuerungen machen keinen Klang: Sie bewegen Regler. Ein LFO ist eine langsame Welle, die auf und ab geht. Füg einen hinzu.', 'Click LFO in the list.': 'Klick in der Liste auf LFO.',
  'Let it move the volume': 'Lass ihn die Lautstärke bewegen', 'Control cables are amber, and plug into the diamond beside a knob.': 'Steuerkabel sind bernsteinfarben und stecken in der Raute neben einem Regler.', 'Drag from the LFO\'s Wave diamond to the diamond beside the Noise\'s Volume. Listen: the sea starts to breathe.': 'Zieh von der Wellen-Raute des LFO zur Raute neben der Lautstärke des Rauschens. Hör hin: Das Meer beginnt zu atmen.', 'Drag from the amber diamond to the Volume diamond.': 'Zieh von der bernsteinfarbenen Raute zur Lautstärke-Raute.',
  'Shape the waves': 'Form die Wellen', 'Depth is how far the LFO swings the knob. Turn it down to about 0.6, so the water pulls back between waves instead of cutting out.': 'Tiefe ist, wie weit der LFO den Regler schwingt. Dreh sie auf etwa 0.6 herunter, damit sich das Wasser zwischen den Wellen zurückzieht statt abzubrechen.', 'Speed sets how often: 0.10 Hz is one wave every ten seconds.': 'Geschwindigkeit bestimmt, wie oft: 0.10 Hz ist eine Welle alle zehn Sekunden.', 'Drag Depth to about 0.6.': 'Zieh Tiefe auf etwa 0.6.',
  'Make it a file': 'Mach eine Datei daraus', 'Render a loop plays the soundscape here, silently and faster than real time, and saves a WAV that loops without a seam. Open it.': '„Schleife rendern“ spielt die Klanglandschaft hier ab, lautlos und schneller als in Echtzeit, und speichert eine nahtlos wiederholbare WAV. Öffne es.', 'Press Render a loop.': 'Drück „Schleife rendern“.',
  'Render it': 'Render sie', '30 seconds is plenty for a first loop: drag Length down if you like, then press Render.': '30 Sekunden reichen für eine erste Schleife: Zieh die Länge herunter, wenn du magst, und drück Rendern.', 'It\'s saved to Music › Critter Sounds › Loops, ready for a playlist, a sound pad, or any other player.': 'Sie wird in Musik › Critter Sounds › Loops gespeichert, bereit für eine Playlist, ein Sound-Pad oder jeden anderen Player.', 'Press Render.': 'Drück Rendern.',
  'Your first loop is done': 'Deine erste Schleife ist fertig', 'It\'s in Music › Critter Sounds › Loops. This soundscape saved itself too, so its tile in the main window plays it live.': 'Sie liegt in Musik › Critter Sounds › Loops. Diese Klanglandschaft hat sich auch selbst gespeichert, ihre Kachel im Hauptfenster spielt sie also live.', 'Ideas for next time:': 'Ideen für das nächste Mal:',
  'A Filter after the Noise (lowpass) makes the sea sound farther away': 'Ein Filter nach dem Rauschen (Tiefpass) lässt das Meer ferner klingen', 'Sometimes → Sample plays a seagull or a ship\'s bell now and then': 'Manchmal → Sample spielt ab und zu eine Möwe oder eine Schiffsglocke', 'A Macro shows up as a slider on the soundscape\'s tile, to steer it during a game': 'Ein Makro erscheint als Regler auf der Kachel der Klanglandschaft, um sie im Spiel zu steuern', 'Double-click the canvas (or press Tab) to find any node by name': 'Doppelklick auf die Arbeitsfläche (oder Tab) findet jeden Knoten nach Namen',

  // ---------- Einrichtung ----------
  'Skip setup': 'Einrichtung überspringen', 'Let\'s go': 'Los geht\'s', 'Setup skipped. Help › Setup brings it back.': 'Einrichtung übersprungen. Hilfe › Einrichtung holt sie zurück.', 'All set. Help › Quick tour shows you around any time.': 'Alles bereit. Hilfe › Kurztour zeigt dir jederzeit alles.',
  'Music, sound effects and ambience for your tabletop game, played live to everyone at your table: in Critter VTT, or in a Discord or Fluxer voice channel.': 'Musik, Soundeffekte und Atmosphäre für dein Tabletop-Spiel, live gespielt für alle an deinem Tisch: in Critter VTT oder in einem Discord- oder Fluxer-Sprachkanal.', 'Three quick questions set it up for you. You can skip, and change everything later.': 'Drei kurze Fragen richten alles ein. Du kannst überspringen und später alles ändern.',
  'Where does your group listen?': 'Wo hört deine Gruppe zu?', 'In Critter VTT': 'In Critter VTT', 'Everyone hears it in their own Critter VTT, with their own volume.': 'Alle hören es in ihrem eigenen Critter VTT, mit eigener Lautstärke.', 'The lobby owner finds the music code in Critter VTT\'s Music window. You can also paste it into the top bar later.': 'Der Lobby-Besitzer findet den Musikcode in Critters Musikfenster. Du kannst ihn auch später in die obere Leiste einfügen.', 'Music code, like 4TBCEF-EMJQE-SQSW5': 'Musikcode, etwa 4TBCEF-EMJQE-SQSW5', 'Connecting to the table…': 'Verbinde mit dem Tisch…',
  'In Discord or Fluxer': 'In Discord oder Fluxer', 'A bot of your own plays into your voice channel. Its window opens when setup is done.': 'Ein eigener Bot spielt in deinen Sprachkanal. Sein Fenster öffnet sich nach der Einrichtung.', 'Only here, on this computer': 'Nur hier, an diesem Computer', 'For trying it out, or a table where everyone sits in one room.': 'Zum Ausprobieren oder für einen Tisch, an dem alle in einem Raum sitzen.',
  'Where is your music?': 'Wo ist deine Musik?', 'A folder on this computer': 'Ein Ordner auf diesem Computer', 'Pick a folder: it becomes a playlist. Nothing is uploaded.': 'Wähle einen Ordner: Er wird zur Playlist. Nichts wird hochgeladen.', 'Choose…': 'Wählen…', 'Free music and sounds online': 'Freie Musik und Klänge online', 'Tabletop Audio, Incompetech, Freesound and more. The online library opens when setup is done.': 'Tabletop Audio, Incompetech, Freesound und mehr. Die Online-Bibliothek öffnet sich nach der Einrichtung.', 'I\'ll add it later': 'Ich füge sie später hinzu', 'Playlists › From a folder, whenever you like.': 'Playlists › Aus einem Ordner, wann immer du willst.',
  'Pick a layout': 'Wähle ein Layout', 'A layout is a set of windows. Change it any time with Layouts in the top bar.': 'Ein Layout ist eine Fenster-Zusammenstellung. Ändere es jederzeit über Layouts in der oberen Leiste.', 'Start with nothing and add windows yourself': 'Mit nichts anfangen und selbst Fenster hinzufügen',
  'Want a quick look around?': 'Lust auf einen kurzen Rundgang?', 'About two minutes: the screen, playing, and arranging windows.': 'Etwa zwei Minuten: der Bildschirm, Abspielen und Fenster anordnen.', 'About ten minutes: every window, and what you can do with it.': 'Etwa zehn Minuten: jedes Fenster und was du damit tun kannst.', 'No thanks': 'Nein danke', 'Both tours are in Help, any time.': 'Beide Touren findest du jederzeit in der Hilfe.', 'Start the tour': 'Tour starten',

  // ---------- Bots ----------
  'No Critter VTT? Play to a voice channel instead. A bot of your own joins Discord or Fluxer and plays exactly what the table would hear, effects included. It works alongside Critter VTT too.': 'Kein Critter VTT? Spiel stattdessen in einen Sprachkanal. Ein eigener Bot tritt Discord oder Fluxer bei und spielt genau, was der Tisch hören würde, mit Effekten. Das geht auch zusätzlich zu Critter VTT.',
  'Voice chat compresses sound more than Critter VTT does, so quiet ambiences can sound thinner. Keep "Here" off while listening in the voice channel, or you\'ll hear everything twice.': 'Sprachchat komprimiert Klang stärker als Critter VTT, leise Atmosphären können daher dünner klingen. Lass „Hier“ aus, während du im Sprachkanal zuhörst, sonst hörst du alles doppelt.',
  '⟳ Reconnect': '⟳ Neu verbinden', '⟳ Sign in': '⟳ Anmelden', '⟳ Signing in…': '⟳ Melde an…', 'Sign in again with the saved token (and go back to the channel it was in)': 'Mit dem gespeicherten Token neu anmelden (und zurück in den vorherigen Kanal)', 'Token, invite and more': 'Token, Einladung und mehr', '＋ Add the bot\'s token': '＋ Token des Bots hinzufügen', '? How': '? Wie',
  'Signing in…': 'Melde an…', 'Signed in': 'Angemeldet', 'Not signed in': 'Nicht angemeldet', 'Signed out': 'Abgemeldet', 'No bot yet': 'Noch kein Bot', 'Joining…': 'Trete bei…',
  'Signing in with the saved token…': 'Melde mit dem gespeicherten Token an…', 'Signed out. It signs in again when Critter Sounds starts.': 'Abgemeldet. Beim nächsten Start von Critter Sounds meldet er sich wieder an.', 'It couldn\'t sign in. Check the connection, or change the token in ⋯.': 'Die Anmeldung hat nicht geklappt. Prüf die Verbindung oder ändere den Token unter ⋯.',
  'The bot isn\'t in any server yet: invite it first.': 'Der Bot ist noch in keinem Server: Lade ihn zuerst ein.', 'Invite it to a server': 'Zu einem Server einladen', 'No voice channel the bot can see here.': 'Hier gibt es keinen Sprachkanal, den der Bot sehen kann.', 'The bot may not speak here': 'Der Bot darf hier nicht sprechen', 'The bot is here': 'Der Bot ist hier', 'Join this channel': 'Diesem Kanal beitreten', 'Playing here; nobody else is in it yet': 'Spielt hier; sonst ist noch niemand da',
  'The bot may not connect or speak here: give it Connect and Speak in this channel': 'Der Bot darf hier nicht verbinden oder sprechen: Gib ihm in diesem Kanal „Verbinden“ und „Sprechen“',
  'Post what plays in the channel\'s chat': 'Im Chat des Kanals posten, was läuft', 'A short line in the voice channel\'s text chat when a track or web page starts, with its credit': 'Eine kurze Zeile im Textchat des Sprachkanals, wenn ein Titel oder eine Webseite beginnt, mit Quellenangabe', 'Join the last channel on start': 'Beim Start dem letzten Kanal beitreten', 'When Critter Sounds starts, the bot signs in and goes back to the last channel': 'Wenn Critter Sounds startet, meldet sich der Bot an und geht zurück in den letzten Kanal',
  'Change the token…': 'Token ändern…', 'Add the token…': 'Token hinzufügen…', 'How to make a bot': 'So erstellst du einen Bot', 'Sign out until next start': 'Bis zum nächsten Start abmelden', 'Forget the token': 'Token vergessen',
  'Paste the new token': 'Neuen Token einfügen', 'Paste the bot\'s token': 'Token des Bots einfügen', 'Paste the bot\'s token first.': 'Füge zuerst den Token des Bots ein.', 'Your own Fluxer\'s address (leave empty for fluxer.app)': 'Adresse deines eigenen Fluxer (leer lassen für fluxer.app)', 'Save and sign in': 'Speichern und anmelden', '? How to make a bot': '? So erstellst du einen Bot',
  'It\'s kept encrypted on this computer, and the bot signs in with it whenever Critter Sounds starts.': 'Er wird verschlüsselt auf diesem Computer aufbewahrt, und der Bot meldet sich damit bei jedem Start von Critter Sounds an.', ' Leave it empty to keep the saved one.': ' Lass das Feld leer, um den gespeicherten zu behalten.',
  'Your group hears Critter Sounds in a voice channel, through a bot that only you control. Nothing goes through anyone else\'s server, and there\'s no shared bot to get banned or rate-limited.': 'Deine Gruppe hört Critter Sounds in einem Sprachkanal, über einen Bot, den nur du steuerst. Nichts läuft über fremde Server, und es gibt keinen geteilten Bot, der gesperrt oder gedrosselt werden könnte.',
  'Open the Discord Developer Portal (discord.com/developers/applications) and press New Application. Name it, for example "Table music".': 'Öffne das Discord Developer Portal (discord.com/developers/applications) und drück „New Application“. Benenne sie, zum Beispiel „Tischmusik“.', 'Under Bot, press Reset Token and copy the token. Keep it secret: anyone with it can use your bot.': 'Drück unter „Bot“ auf „Reset Token“ und kopiere den Token. Halte ihn geheim: Jeder, der ihn hat, kann deinen Bot benutzen.', 'Paste the token here and press Connect.': 'Füge den Token hier ein und drück Verbinden.',
  'Press "Invite it to a server" (or under OAuth2, make an invite link with the bot scope and the Connect, Speak and Send Messages permissions) and add it to your server.': 'Drück „Zu einem Server einladen“ (oder erstelle unter OAuth2 einen Einladungslink mit dem Bereich „bot“ und den Rechten Verbinden, Sprechen und Nachrichten senden) und füge ihn deinem Server hinzu.', 'Pick the voice channel and press Join. Everyone in that channel hears what you play, with your effects.': 'Wähle den Sprachkanal und drück Beitreten. Alle in diesem Kanal hören, was du spielst, mit deinen Effekten.',
  'In Fluxer\'s developer portal, create an application with a bot. Name it, for example "Table music".': 'Erstelle im Entwicklerportal von Fluxer eine Anwendung mit einem Bot. Benenne sie, zum Beispiel „Tischmusik“.', 'Copy the bot\'s token. Keep it secret: anyone with it can use your bot.': 'Kopiere den Token des Bots. Halte ihn geheim: Jeder, der ihn hat, kann deinen Bot benutzen.', 'Invite the bot to your community with the invite (OAuth2) link the portal gives you, with permission to connect and speak in voice.': 'Lade den Bot mit dem Einladungslink (OAuth2) aus dem Portal in deine Community ein, mit dem Recht, in Sprachkanälen zu verbinden und zu sprechen.',
  'Paste the token here and press Connect. On a Fluxer you host yourself, fill in its address first.': 'Füge den Token hier ein und drück Verbinden. Bei einem selbst betriebenen Fluxer trag zuerst seine Adresse ein.', 'Pick the voice channel and press Join.': 'Wähle den Sprachkanal und drück Beitreten.',
  'The bot plays your mix as a live stream: playlists, pads, soundscapes and web pages, after the effects. The token is stored encrypted on this computer.': 'Der Bot spielt deine Mischung als Livestream: Playlists, Pads, Klanglandschaften und Webseiten, nach den Effekten. Der Token wird verschlüsselt auf diesem Computer gespeichert.', 'Open the Developer Portal': 'Developer Portal öffnen', 'Open Fluxer': 'Fluxer öffnen',
  'That token wasn\'t accepted: copy it again from the Developer Portal (Bot › Reset Token).': 'Dieser Token wurde nicht akzeptiert: Kopiere ihn nochmal aus dem Developer Portal (Bot › Reset Token).', 'That token wasn\'t accepted: copy the bot token again from your Fluxer application.': 'Dieser Token wurde nicht akzeptiert: Kopiere den Bot-Token nochmal aus deiner Fluxer-Anwendung.',
  'Connect the bot first.': 'Verbinde zuerst den Bot.', 'That isn\'t a voice channel.': 'Das ist kein Sprachkanal.', 'The bot may not join that channel: give it Connect and Speak there.': 'Der Bot darf diesem Kanal nicht beitreten: Gib ihm dort „Verbinden“ und „Sprechen“.', 'The voice connection was lost.': 'Die Sprachverbindung ist abgebrochen.', 'That channel isn\'t there any more.': 'Diesen Kanal gibt es nicht mehr.', 'This Fluxer server\'s voice isn\'t the LiveKit kind Critter Sounds can stream to.': 'Die Sprachfunktion dieses Fluxer-Servers ist nicht die LiveKit-Art, an die Critter Sounds streamen kann.',

  // ---------- Verbindung ----------
  'Choose a Homebase first: the same one your table uses.': 'Wähle zuerst eine Homebase: dieselbe, die dein Tisch nutzt.', 'Could not reach Homebase. Check your connection and the Homebase setting.': 'Homebase war nicht erreichbar. Prüf deine Verbindung und die Homebase-Einstellung.',
  'That music code is out of date: the owner made a new one. Copy it again from Critter VTT\'s Music window.': 'Dieser Musikcode ist veraltet: Der Besitzer hat einen neuen erstellt. Kopiere ihn nochmal aus Critters Musikfenster.', 'The lobby owner hasn\'t made a music code yet (Critter VTT › Music), so the table won\'t play this app.': 'Der Lobby-Besitzer hat noch keinen Musikcode erstellt (Critter VTT › Musik), der Tisch spielt diese App also nicht.',
  'Another Critter Sounds app is in this lobby too. The table plays whichever joined first.': 'In dieser Lobby ist noch eine Critter Sounds-App. Der Tisch spielt die, die zuerst beigetreten ist.', 'Playing to the table': 'Spielt für den Tisch',
  'Any colour you like': 'Jede Farbe, die du magst', 'Highlight': 'Akzent', 'Second highlight': 'Zweiter Akzent', 'Background': 'Hintergrund', 'Back to Critter Sounds colours': 'Zurück zu den Farben von Critter Sounds', 'Midnight': 'Mitternacht', 'Black': 'Schwarz', 'Slate': 'Schiefer', 'Lilac': 'Flieder', 'Gold': 'Gold', 'Ember': 'Glut', 'Crimson': 'Karmesin', 'Rose': 'Rose', 'Emerald': 'Smaragd', 'Teal': 'Petrol', 'Azure': 'Azur', 'Ice': 'Eis',
  'Buttons, the playing track, sliders and selections.': 'Knöpfe, der laufende Titel, Regler und Auswahlen.', 'Previews, the level meter and other details.': 'Vorhören, die Pegelanzeige und andere Details.',
  'That file couldn\'t be read as an impulse response. Use a short WAV recording of a space.': 'Diese Datei ließ sich nicht als Impulsantwort lesen. Nutze eine kurze WAV-Aufnahme eines Raums.',

  // ---------- Einstellungen, Ordner, Hinweise (neu) ----------
  'Settings': 'Einstellungen', 'Language': 'Sprache', 'System language': 'Systemsprache', 'Open the Critter Sounds folder (music, downloads, loops)': 'Den Ordner von Critter Sounds öffnen (Musik, Downloads, Schleifen)', 'Hide this tip': 'Diesen Hinweis ausblenden', 'Show all tips again': 'Alle Hinweise wieder zeigen', 'All tips are back.': 'Alle Hinweise sind wieder da.', 'Tips and help': 'Hinweise und Hilfe',
});
// Texte mit Werten darin: [englisches Muster, deutsche Fassung (mit $1, $2… oder als Funktion)]
window.I18N_DE_P = [
  [/^(\d+) selected$/, '$1 ausgewählt'], [/^(\d+) in the queue$/, '$1 in der Warteschlange'], [/^Up next (\d+)$/, 'Als Nächstes $1'], [/^All (\d+)$/, 'Alle $1'],
  [/^Discord bot joined (.+)$/, 'Discord-Bot ist $1 beigetreten'], [/^Fluxer bot joined (.+)$/, 'Fluxer-Bot ist $1 beigetreten'], [/^(Discord|Fluxer): playing in (.+)\.$/, '$1: spielt in $2.'], [/^(Discord|Fluxer) bot token$/, '$1-Bot-Token'], [/^A (Discord|Fluxer) bot of your own$/, 'Ein eigener $1-Bot'],
  [/^Make a (Discord|Fluxer) bot of your own, add its token, and it signs in whenever Critter Sounds starts\.$/, 'Erstelle einen eigenen $1-Bot, füge seinen Token hinzu, und er meldet sich bei jedem Start von Critter Sounds an.'],
  [/^Forget the (Discord|Fluxer) bot's token\? It signs out and won't sign in again on start\.$/, 'Den Token des $1-Bots vergessen? Er meldet sich ab und beim Start nicht wieder an.'],
  [/^Signed in as (.+)$/, 'Angemeldet als $1'], [/^Playing in (.+)$/, 'Spielt in $1'], [/^Playing for (.+)$/, 'Spielt für $1'],
  [/^(\d+) tracks?(.*)$/, (m, n, r) => `${n} ${n === '1' ? 'Titel' : 'Titel'}${r}`], [/^Add (\d+) to the queue$/, '$1 zur Warteschlange hinzufügen'], [/^Remove (\d+) tracks$/, '$1 Titel entfernen'], [/^Removed (\d+) tracks?\.$/, '$1 Titel entfernt.'],
  [/^Added (\d+) tracks? to (.+)\.$/, '$1 Titel zu $2 hinzugefügt.'], [/^Added (\d+) to (.+)\.$/, '$1 zu $2 hinzugefügt.'], [/^(.+) already has (them|it)\.$/, (m, a, b) => `${a} enthält ${b === 'it' ? 'ihn' : 'sie'} schon.`],
  [/^Queued (.+)\.$/, '$1 eingereiht.'], [/^Plays next: (.+)\.$/, 'Als Nächstes: $1.'], [/^Couldn't play (.+)\. Skipping it\.$/, '$1 ließ sich nicht abspielen. Wird übersprungen.'], [/^Couldn't play (.+)\.$/, '$1 ließ sich nicht abspielen.'],
  [/^Delete the playlist "(.+)"\? The music files stay where they are\.$/, 'Die Playlist „$1“ löschen? Die Musikdateien bleiben, wo sie sind.'], [/^Deleted "(.+)"\.$/, '„$1“ gelöscht.'], [/^Saved the layout "(.+)"\.$/, 'Layout „$1“ gespeichert.'],
  [/^Move "(.+)" to the recycle bin\?$/, '„$1“ in den Papierkorb verschieben?'], [/^Icon for "(.+)"$/, 'Symbol für „$1“'], [/^Colour of "(.+)"$/, 'Farbe von „$1“'], [/^Every pad tagged "(.+)" takes this colour\.$/, 'Jedes Pad mit dem Tag „$1“ übernimmt diese Farbe.'],
  [/^Made (\d+) sound pads\.$/, '$1 Sound-Pads angelegt.'], [/^(.+) is a sound pad now\.$/, '$1 ist jetzt ein Sound-Pad.'], [/^Sound pads playing \((\d+)\)$/, 'Laufende Sound-Pads ($1)'],
  [/^Brought in (\d+) soundscapes?\.$/, '$1 Klanglandschaft(en) hereingeholt.'], [/^(\d+) nodes?( · playing)?$/, (m, n, p) => `${n} Knoten${p ? ' · läuft' : ''}`], [/^Playing: (.+)$/, 'Läuft: $1'], [/^Soundscape: (.+)$/, 'Klanglandschaft: $1'], [/^Scene: (.+)$/, 'Szene: $1'], [/^Effects: (.+)$/, 'Effekte: $1'],
  [/^Your node (.+) has a problem: (.+)$/, 'Dein Knoten $1 hat ein Problem: $2'], [/^(\d+) nodes? in "(.+)" could not start: (.+)$/, '$1 Knoten in „$2“ konnte(n) nicht starten: $3'], [/^Problem: (.+)$/, 'Problem: $1'], [/^Not saved: (.+)$/, 'Nicht gespeichert: $1'],
  [/^Rendering… (\d+)%$/, 'Rendere… $1 %'], [/^Done in ([\d.]+) s: (.+?)( \(it was turned down a little so it doesn't clip\))?$/, (m, s, f, q) => `Fertig in ${s} s: ${f}${q ? ' (etwas leiser gemacht, damit nichts übersteuert)' : ''}`], [/^It could not be rendered: (.+)$/, 'Sie konnte nicht gerendert werden: $1'],
  [/^Done: "(.+)" with (\d+) tracks?\.$/, 'Fertig: „$1“ mit $2 Titel(n).'], [/^Downloaded "(.+)" into the YouTube playlist\.$/, '„$1“ in die YouTube-Playlist heruntergeladen.'], [/^Downloaded (\d+) into the YouTube playlist\.$/, '$1 in die YouTube-Playlist heruntergeladen.'], [/^Couldn't download "(.+)": (.+)$/, '„$1“ konnte nicht heruntergeladen werden: $2'], [/^Saving (.+)…$/, 'Speichere $1…'], [/^Saved to (.+)\. It plays from there now, even offline\.$/, 'Gespeichert in $1. Es spielt jetzt von dort, auch offline.'],
  [/^yt-dlp (.+) is installed\.$/, 'yt-dlp $1 ist installiert.'], [/^Loading (.+)'s list…$/, 'Lade die Liste von $1…'], [/^Couldn't load (.+?): (.+)$/, '$1 konnte nicht geladen werden: $2'], [/^Search (\d+) pieces: medieval, tense, harp…$/, '$1 Stücke durchsuchen: mittelalterlich, spannend, Harfe…'], [/^Search (\d+) tracks: tavern, storm, spaceship…$/, '$1 Titel durchsuchen: Taverne, Sturm, Raumschiff…'], [/^Show more \((\d+) left\)$/, 'Mehr zeigen (noch $1)'], [/^(\d+) found(.*)$/, '$1 gefunden$2'],
  [/^Copied (\d+) credits?\. Paste them in your stream or video description\.$/, '$1 Quellenangabe(n) kopiert. Füge sie in deine Stream- oder Videobeschreibung ein.'],
  [/^Stops in (\d+) min$/, 'Stopp in $1 Min.'], [/^The music fades out and stops in (\d+) minutes\.$/, 'Die Musik blendet aus und stoppt in $1 Minuten.'], [/^Then from (.+?)( \(shuffled\))?$/, (m, p, s) => `Danach aus ${p}${s ? ' (gemischt)' : ''}`],
  [/^No lobby uses the code (\w+) on this Homebase\. Check the code, and that this app uses the same Homebase as the table\.$/, 'Keine Lobby nutzt den Code $1 auf dieser Homebase. Prüf den Code und ob diese App dieselbe Homebase nutzt wie der Tisch.'], [/^(\w+) · (\d+)\/(\d+) hearing it$/, '$1 · $2/$3 hören zu'],
  [/^Plug into… \((.+)\)$/, (m, k) => `Anschließen an… (${({ Sound: 'Klang', Control: 'Steuerung', Trigger: 'Auslöser' })[k] || k})`], [/^(.+): (Sound|Control|Trigger) (in|out)$/, (m, a, k, d) => `${a}: ${({ Sound: 'Klang', Control: 'Steuerung', Trigger: 'Auslöser' })[k]} ${d === 'in' ? 'Eingang' : 'Ausgang'}`],
  [/^(\d+) of (\d+)$/, '$1 von $2'], [/^Done: "(.+)" with/, 'Fertig: „$1“ mit'], [/^Could not (.+?): (.+)$/, null], [/^(.+): soundscape editor$/, '$1: Klanglandschafts-Editor'],
];
// Einstellungen, Hinweise und Statuszeilen
Object.assign(window.I18N_DE, {
  'General': 'Allgemein', 'Your name at the table': 'Dein Name am Tisch', 'Connect to the last table on start': 'Beim Start mit dem letzten Tisch verbinden', 'Uses the music code from last time.': 'Nutzt den Musikcode vom letzten Mal.',
  'Ask before quitting while something plays': 'Vor dem Beenden fragen, wenn etwas läuft', 'Media keys work even when the app is in the background': 'Medientasten wirken auch, wenn die App im Hintergrund ist', 'Play, pause, next, previous and stop on the keyboard.': 'Abspielen, Pause, Weiter, Zurück und Stopp auf der Tastatur.',
  'Music dips under pads to': 'Musik sinkt unter Pads auf', 'Preview volume': 'Lautstärke beim Vorhören', 'Show what plays in Critter VTT\'s chat': 'In Critters Chat zeigen, was läuft', 'Small notes in the lobby\'s chat, from the session log.': 'Kleine Notizen im Chat der Lobby, aus dem Sitzungsprotokoll.',
  'Folders': 'Ordner', 'Downloads, YouTube, soundscapes and rendered loops go here. Moving it doesn\'t move what\'s already saved.': 'Hier landen Downloads, YouTube, Klanglandschaften und gerenderte Schleifen. Ein Umzug verschiebt nichts, was schon gespeichert ist.', '📂 Open': '📂 Öffnen', 'Change…': 'Ändern…', 'Back to the Music folder': 'Zurück zum Musik-Ordner',
  'Open the app\'s data folder': 'Datenordner der App öffnen', 'Your library, settings and bot tokens': 'Deine Bibliothek, Einstellungen und Bot-Tokens', 'Back up the library…': 'Bibliothek sichern…', 'Playlists, pads, scenes, layouts and settings, as one file': 'Playlists, Pads, Szenen, Layouts und Einstellungen in einer Datei',
  'Connection': 'Verbindung', 'Homebase connects this app to Critter VTT. Use the same one as your table.': 'Homebase verbindet diese App mit Critter VTT. Nutze dieselbe wie dein Tisch.', 'Homebase…': 'Homebase…', 'Run the setup again': 'Einrichtung erneut starten', 'Reset all settings': 'Alle Einstellungen zurücksetzen',
  'Puts every setting back as it was at first. Playlists, pads, scenes, soundscapes and layouts stay.': 'Setzt alle Einstellungen auf den Anfang zurück. Playlists, Pads, Szenen, Klanglandschaften und Layouts bleiben.', 'Reset all settings? Playlists, pads, scenes, soundscapes and layouts stay.': 'Alle Einstellungen zurücksetzen? Playlists, Pads, Szenen, Klanglandschaften und Layouts bleiben.',
  'The light blue boxes you closed with ✕': 'Die hellblauen Kästen, die du mit ✕ geschlossen hast', 'Language, folders, keys and more': 'Sprache, Ordner, Tasten und mehr', 'Settings…': 'Einstellungen…', 'English': 'English', 'Deutsch': 'Deutsch',
  'Downloads only the sound, into Music › Critter Sounds › YouTube, and adds it to your "YouTube" playlist. Please download only what you may use: your own videos, Creative Commons ones, or with the creator\'s permission. YouTube\'s terms don\'t allow other downloads.': 'Lädt nur den Ton herunter, nach Musik › Critter Sounds › YouTube, und fügt ihn deiner Playlist „YouTube“ hinzu. Bitte lade nur herunter, was du nutzen darfst: eigene Videos, Creative-Commons-Videos oder mit Erlaubnis der Urheber. Die Bedingungen von YouTube erlauben keine anderen Downloads.',
  'From the queue': 'Aus der Warteschlange', 'From the web page': 'Von der Webseite', 'Saving failed: ': 'Speichern fehlgeschlagen: ', 'live': 'live'
});
window.I18N_DE_P.push(
  [/^From the queue · (.+)$/, 'Aus der Warteschlange · $1'], [/^From (.+?)( · .+)?$/, (m, a, r) => `Aus ${a}${r || ''}`], [/^Saved a backup: (.+)$/, 'Sicherung gespeichert: $1'], [/^New downloads and loops go to (.+)$/, 'Neue Downloads und Schleifen landen in $1'], [/^Saving failed: (.+)$/, 'Speichern fehlgeschlagen: $1'], [/^(.+), online$/, '$1, online']
);
// was beim Durchsehen noch englisch war
Object.assign(window.I18N_DE, {
  'Show it': 'Zeigen', 'Close it': 'Schließen', 'Plays once (click to loop it)': 'Spielt einmal (klicken zum Wiederholen)', 'Looping: it plays until you stop it (click to play once)': 'Wiederholt: spielt, bis du es stoppst (klicken für einmal)',
  'Opens in its own window. Sign in or pick a video there; the sound goes to the table through the same fades, volume and effects. Turn on "Here" in the bar to hear it yourself.': 'Öffnet sich in einem eigenen Fenster. Melde dich dort an oder wähle ein Video; der Ton geht mit denselben Blenden, derselben Lautstärke und denselben Effekten an den Tisch. Schalte „Hier“ in der Leiste ein, um selbst mitzuhören.',
  'https://www.youtube.com/…  or any page that plays sound': 'https://www.youtube.com/…  oder jede Seite mit Ton',
  'Ambiences and music by Tim Card, free under': 'Atmosphären und Musik von Tim Card, frei unter', '. Fine for your games and for small streams with credit. If you use it a lot,': '. In Ordnung für eure Spiele und kleine Streams mit Quellenangabe. Wenn du es viel nutzt,', 'support it on Patreon': 'unterstütze es auf Patreon',
  'Add it to the queue; it plays after what\'s playing': 'Zur Warteschlange hinzufügen; spielt nach dem, was gerade läuft',
  '◫ and ⊟ split a window to the right or below. Drag the line between two windows to resize them; it clicks into place at halves, thirds and quarters (hold Alt to place it freely). Double-click the line to make both halves equal.': '◫ und ⊟ teilen ein Fenster nach rechts oder unten. Zieh die Linie zwischen zwei Fenstern, um ihre Größe zu ändern; sie rastet bei Hälften, Dritteln und Vierteln ein (Alt halten für freie Platzierung). Doppelklick auf die Linie macht beide Hälften gleich.',
  'Stop with a fade; press again to stop at once': 'Mit Ausblenden stoppen; nochmal drücken stoppt sofort', 'Next: the queue first, then the playlist': 'Weiter: erst die Warteschlange, dann die Playlist', 'Previous track (or back to the start)': 'Vorheriger Titel (oder zurück zum Anfang)', 'Jump back or ahead 10 seconds': '10 Sekunden zurück oder vor', 'Add the selected tracks to the queue': 'Die ausgewählten Titel zur Warteschlange hinzufügen', 'Mini player, which stays on top': 'Mini-Player, der im Vordergrund bleibt', 'Search the window in focus': 'Das aktive Fenster durchsuchen', 'Remove the selected tracks': 'Die ausgewählten Titel entfernen', 'Play, pause, next, previous and stop work from any app': 'Abspielen, Pause, Weiter, Zurück und Stopp funktionieren aus jeder App',
  'The queue on the right plays first; then the playlist you last played from carries on. A track leaves the queue when it starts.': 'Die Warteschlange rechts spielt zuerst; danach geht es mit der zuletzt gespielten Playlist weiter. Ein Titel verlässt die Warteschlange, wenn er beginnt.',
  'Windows': 'Fenster', 'Media keys': 'Medientasten'
});
// the ⋯ in narrow title bars
Object.assign(window.I18N_DE, { 'This window\'s buttons': 'Knöpfe dieses Fensters' });
// Appearance: the shared Critter VTT look
Object.assign(window.I18N_DE, {
  'Light or dark': 'Hell oder dunkel', 'Dark': 'Dunkel', 'Light': 'Hell', 'Surface tint': 'Flächentönung',
  'How much the highlight colours the background and the windows.': 'Wie stark der Akzent den Hintergrund und die Fenster einfärbt.',
  'Picture colour': 'Bildfarbe', 'How far the cover of what\'s playing spills its colours into the bar.': 'Wie weit das Cover des laufenden Titels seine Farben in die Leiste strahlen lässt.',
  'Off': 'Aus', 'Soft': 'Sanft', 'Full': 'Voll', 'Fonts': 'Schriften', 'The dragon rolls a 20': 'Der Drache würfelt eine 20', 'Easy reading': 'Leicht lesbar',
  'That\'s only the lobby code. Paste the whole music code from Critter VTT\'s Music window (the lobby owner has it); the table only plays music from an app that has it.': 'Das ist nur der Lobbycode. Füge den ganzen Musikcode aus dem Musikfenster von Critter VTT ein (der Lobbybesitzer hat ihn); der Tisch spielt nur Musik aus einer App, die ihn hat.'
});
// ---------- Aktualisierungen ----------
Object.assign(window.I18N_DE, {
  'Updates': 'Aktualisierungen', 'Check for updates…': 'Nach Aktualisierungen suchen…', 'Check for updates': 'Nach Aktualisierungen suchen', 'A newer Critter Sounds, from GitHub': 'Ein neueres Critter Sounds, von GitHub',
  'Critter Sounds on GitHub': 'Critter Sounds auf GitHub', 'The code, the releases and what changed': 'Der Code, die Versionen und was sich geändert hat',
  'Check for updates when Critter Sounds starts': 'Beim Start von Critter Sounds nach Aktualisierungen suchen', 'A quiet look a few seconds after starting; it only speaks up when there is something new.': 'Ein stiller Blick ein paar Sekunden nach dem Start; es meldet sich nur, wenn es etwas Neues gibt.',
  'Made with love by booskers / Polychrome.': 'Mit Liebe gemacht von booskers / Polychrome.'
});
// design standard: film grain and the buttons' new words
Object.assign(window.I18N_DE, { 'Film grain': 'Filmkorn', 'A fine grain over the background, like film.': 'Ein feines Korn über dem Hintergrund, wie bei Film.', 'Off': 'Aus', 'On': 'An' });
